spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: consumer
          uri: lb://dubbo-consumer
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: provider
          uri: lb://dubbo-provider
          predicates:
            - Path=/stock/**
          filters:
            - StripPrefix=1