spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: consumer
          uri: lb://dubbo-consumer
          predicates:
            - Path=/app-order/**
          filters:
            - StripPrefix=1
        - id: provider
          uri: lb://provider
#          uri: http://localhost:8082
          predicates:
            - Path=/app-stock/**
          filters:
            - StripPrefix=1
        - id: provider
          uri: lb://user-login
#          uri: http://localhost:8082
          predicates:
            - Path=/app-login/**
          filters:
            - StripPrefix=1
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: always
